[project]
name = "espnet"
dynamic = ["version", "readme"]
authors = [
    {name="Shinji Watanabe", email="shinjiw@ieee.org"}
]
description = "ESPnet: end-to-end speech processing toolkit"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
license = { "text" = "Apache Software License" }
dependencies = [
    "setuptools>70.0.0",
    "configargparse>=1.2.1",
    "packaging",
    "typeguard",
    "humanfriendly",
    "scipy>=1.4.1",
    "numpy",
    "PyYAML>=5.1.2",
    "soundfile>=0.10.2",
]

[project.urls]
Homepage = "http://github.com/espnet/espnet"

[build-system]
requires = ["setuptools>=70.0.0", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "espnet.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
include = ["espnet*"]

[tool.setuptools.package-data]
espnet = ["version.txt"]

[project.optional-dependencies]
core = [
  "torch>=2.6.0",
  "torchaudio>=2.6.0",
  "numpy",
  "soundfile>=0.10.2",
  "kaldiio>=2.18.0",
  "espnet_tts_frontend",
  "sentencepiece==0.2.0",
  "pyworld>=0.3.4",
  "g2p_en",
  "librosa>0.9.2",
  "lightning",
  "nltk>=3.4.5",
  "hydra-core",
]

task-asr = [
  "ctc-segmentation>=1.6.6",
  "editdistance"
]

task-tts = [
  "pyworld>=0.3.4",
  "pypinyin<=0.44.0"
]

task-enh = [
  "ci_sdr",
  "fast-bss-eval==0.1.3"
]

task-spk = [
  "asteroid_filterbanks==0.4.0"
]

dev = [
  "black",
  "flake8",
  "pytest",
  "pytest-cov",
  "isort"
]

test = [
    "pytest>=7.0.0",
    "pytest-timeouts>=1.2.1",
    "pytest-pythonpath>=0.7.3",
    "pytest-cov>=2.7.1",
    "hacking>=2.0.0",
    "mock>=2.0.0",
    "pycodestyle",
    "jsondiff>=2.0.0",
    "flake8>=3.7.8",
    "flake8-docstrings>=1.3.1",
    "black",
    "isort",
]

doc = [
  "sphinx",
  "sphinx-rtd-theme",
  "myst-parser",
  "nbsphinx"
]

all = [
  "espnet[core]",
  "espnet[task-asr]",
  "espnet[task-tts]",
  "espnet[task-enh]",
  "espnet[task-spk]",
  "espnet[recipe-common]"
]
