unused_parameters: true
init: xavier_normal

batch_type: folded
shuffle_within_batch: false
valid_batch_size: 32
batch_size: 32
max_epoch: 250

accum_grad: 1
grad_clip: 1

optim: adamw
optim_conf:
    lr: 3.0e-5 # 1.e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 95000 # 80k steps
    warmup_steps: 8000
    max_lr: 3.0e-5 # 1.e-4
    min_lr: 5.0e-6

freeze_param: [
    "encoder.encoder",
    "encoder.layer_norm",
    "encoder.patch_embedding",
    "encoder.post_extract_proj",
]


patience: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
use_amp: false  # whether to use automatic mixed precision
num_att_plot: 0
num_workers: 2 # dataloader workers

# BEATs implementation takes care of generating mel spectrogram, normalization and specaug
frontend: none
input_size: 1 # important to set input_size to 1 if frontend is none
normalize: none # BEATs code does global mean and variance normalization

encoder: beats
encoder_conf:
    beats_ckpt_path: /work/nvme/bbjs/sbharadwaj/watkins_ssl/exp_cut_tapes_noise/beats_iter0_10k_ckpt.cut_tapes_noise.0.100k_total/epoch10.pt
    beats_config:
        layer_wise_gradient_decay_ratio: 0.3
        encoder_layerdrop: 0.1
        dropout: 0.0
    use_weighted_representation: false
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1
    roll_augment: true
    roll_interval: 1 # 16000

model_conf:
    classification_type: multi-class
    lsm_weight: 0.1  # label smoothing weight, per class
