name: publich docker image

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - 'tools/**'
      - setup.py

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CPU container
        run: |
          cd docker
          docker build --build-arg FROM_TAG=runtime-latest \
            -f prebuilt/devel.dockerfile \
            --target devel \
            -t espnet/espnet:cpu-latest .
          docker push espnet/espnet:cpu-latest

      - name: Build and push GPU container
        run: |
          cd docker
          docker build --build-arg FROM_TAG=cuda-latest \
            --build-arg CUDA_VER=11.1 \
            -f prebuilt/devel.dockerfile \
            --target devel \
            -t espnet/espnet:gpu-latest .
          docker push espnet/espnet:gpu-latest
